### PR TITLE
Add console logger.

### PR DESCRIPTION
**Pull request by ezarko**
By adding a console logger to the constructor, the stand alone server will log messages to the docker container log, conveniently viewable via `docker logs <mock-server-container-name>`.

An alternate approach might be to allow some sort of environment configuration of logging, such as at least a simple switch to turn on console logging. I will leave this up to others.

### CODE REVIEW

**Comment by StefH** [comment]
Good idea !

However I think it's even more usefull if this can be added as a command-line parameter to the https://github.com/WireMock-Net/WireMock.Net/tree/master/src/WireMock.Net.StandAlone application.

I will take a look if this can be implemented there...

**Comment by StefH** [comment]
@ezarko 
Actually, I think that this is already implemented ?

Because when you don't provide a logger, then the default one is used:
https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net/Server/FluentMockServer.cs#L188

**Comment by ezarko** [comment]
What I was seeing was that an slf logger was created instead.  The only thing happening in the docker console logs was endless "WireMock.Net server running". It may have changed since the last publication of the docker image though.

**Comment by ezarko** [comment]
Ah, here is why: https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net/Settings/FluentMockServerSettings.cs#L80

**Comment by StefH** [comment]
Good catch!

**Comment by StefH** [comment]
In the latest version I did add an extra option:
https://github.com/WireMock-Net/WireMock.Net/blob/master/src/WireMock.Net.StandAlone/StandAloneApp.cs#L61

I will update this project to automatically include the console-logger in a docker. Therefore this PR can be closed.

Thanks a lot.

**Pull request closed without merging**
